/**
 * build-reader-html.ts — generates the self-contained WebView HTML for the PDF reader.
 *
 * ASSET-LOADING MECHANISM (documented per spec):
 * We use `source={{ html: buildReaderHtml(pdfJsSrc, pdfWorkerSrc) }}` with pdf.js
 * content injected as inline <script> tags. This avoids file:// URI resolution
 * differences between iOS and Android in Expo Go, requires no custom Metro config,
 * and keeps the reader fully offline (no network).
 *
 * pdf.js and pdf.worker.mjs content is generated at build time by
 * `scripts/bundle-pdfjs.mjs` into `src/reader/pdf-js-content.ts` (gitignored,
 * regenerated by `predev`/`prebuild`). The worker is injected as a Blob URL so
 * pdf.js can find it via `GlobalWorkerOptions.workerSrc`.
 *
 * Reader themes (paper/sepia/night) are applied via `data-reader-theme` on <html>
 * + CSS custom properties that match ui-context.md values exactly (no token pipeline
 * available inside the WebView HTML).
 *
 * Bridge messages:
 *   RN → WebView: { type:'load', bytesBase64 } | { type:'setMode', mode } |
 *                 { type:'setTheme', theme } | { type:'gotoPage', page }
 *   WebView → RN: { type:'ready', numPages } | { type:'page', current } |
 *                 { type:'error', message? } |
 *                 { type:'geometry', pageNumber, viewport:{width,height}, items }
 */

// ── Reader palette (must match ui-context.md exactly — no token pipeline here) ──
// paper #FBF6EC / #2A2422 · sepia #F2E5CC / #4A3F2F · night #14110E / #C9BEAD
const READER_PALETTE = {
  paper: { bg: '#FBF6EC', text: '#2A2422', pageBorder: '#E7DDCB' },
  sepia: { bg: '#F2E5CC', text: '#4A3F2F', pageBorder: '#D4C5A6' },
  night: { bg: '#14110E', text: '#C9BEAD', pageBorder: '#2A2420' },
} as const;

export function buildReaderHtml(pdfJsSrc: string, pdfWorkerSrc: string): string {
  // Build worker blob script — injected inline so pdf.js can set workerSrc to
  // a blob URL. This avoids needing a separate worker file accessible via file://.
  // Classic (non-module) script: runs during parse, BEFORE the pdf.js module.
  // Defines postToRN + global error handlers so that an uncaught error while
  // evaluating the 3MB pdf.js module (or anywhere) is reported to RN instead of
  // leaving the reader on an infinite spinner. Also builds the worker blob URL.
  const workerBlobScript = `
    function postToRN(msg) {
      if (window.ReactNativeWebView) {
        window.ReactNativeWebView.postMessage(JSON.stringify(msg));
      }
    }
    window.__postToRN = postToRN;
    window.addEventListener('error', function (e) {
      postToRN({ type: 'error', message: 'js-error: ' + (e && e.message ? e.message : String(e)) });
    });
    window.addEventListener('unhandledrejection', function (e) {
      postToRN({ type: 'error', message: 'unhandled-rejection: ' + String(e && e.reason) });
    });
    var __workerSrc = (function() {
      var blob = new Blob([${JSON.stringify(pdfWorkerSrc)}], { type: 'application/javascript' });
      return URL.createObjectURL(blob);
    })();
  `;

  const paletteCSS = Object.entries(READER_PALETTE)
    .map(
      ([theme, { bg, text, pageBorder }]) => `
    html[data-reader-theme="${theme}"] {
      --reader-bg: ${bg};
      --reader-text: ${text};
      --reader-page-border: ${pageBorder};
    }`,
    )
    .join('\n');

  return `<!DOCTYPE html>
<html data-reader-theme="paper" lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=3.0">
<title>Ember Reader</title>
<style>
/* ── Reset ── */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

/* ── Reader palette (per-theme, toggled via data-reader-theme) ── */
${paletteCSS}

html, body {
  background: var(--reader-bg, #FBF6EC);
  color: var(--reader-text, #2A2422);
  font-family: -apple-system, system-ui, sans-serif;
  min-height: 100%;
}

/* ── Scroll mode ── */
#scroll-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 24px;
  padding: 24px 12px;
}

/* ── Paged mode ── */
#paged-container {
  display: none;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  padding: 16px 12px 80px;
}

#paged-nav {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
  padding: 12px 16px;
  background: var(--reader-bg, #FBF6EC);
  border-top: 1px solid var(--reader-page-border, #E7DDCB);
}

.nav-btn {
  font-size: 14px;
  padding: 8px 18px;
  border-radius: 6px;
  border: 1px solid var(--reader-page-border, #E7DDCB);
  background: var(--reader-bg, #FBF6EC);
  color: var(--reader-text, #2A2422);
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  transition: opacity 0.15s;
}
.nav-btn:disabled { opacity: 0.3; cursor: default; }
.nav-btn:not(:disabled):active { opacity: 0.6; }

/* ── Page wrapper ── */
.page-wrap {
  position: relative;
  border-radius: 3px;
  overflow: hidden;
  border: 1px solid var(--reader-page-border, #E7DDCB);
  box-shadow: 0 1px 4px rgba(0,0,0,0.08);
  flex-shrink: 0;
}

/* ── Placeholder (unrendered pages in scroll mode) ── */
.page-placeholder {
  background: var(--reader-bg, #FBF6EC);
  border-radius: 3px;
  border: 1px solid var(--reader-page-border, #E7DDCB);
  flex-shrink: 0;
}

/* ── pdf.js text layer (selectable overlay) ──────────────────────────────────
 * Structural rules lifted from pdfjs-dist/web/pdf_viewer.css (v6). The
 * TextLayer renders transparent, absolutely-positioned glyphs over the page
 * canvas so text is selectable. --total-scale-factor is set per-page.
 * ─────────────────────────────────────────────────────────────────────────── */
.textLayer {
  --min-font-size: 1;
  --text-scale-factor: calc(var(--total-scale-factor) * var(--min-font-size));
  --min-font-size-inv: calc(1 / var(--min-font-size));
  position: absolute;
  text-align: initial;
  inset: 0;
  overflow: clip;
  opacity: 1;
  line-height: 1;
  letter-spacing: normal;
  word-spacing: normal;
  text-size-adjust: none;
  forced-color-adjust: none;
  transform-origin: 0 0;
  z-index: 0;
}
.textLayer :is(span, br) {
  color: transparent;
  position: absolute;
  white-space: pre;
  cursor: text;
  transform-origin: 0% 0%;
  -webkit-user-select: text;
  user-select: text;
}
.textLayer > :not(.markedContent),
.textLayer .markedContent span:not(.markedContent) {
  z-index: 1;
  --font-height: 0;
  font-size: calc(var(--text-scale-factor) * var(--font-height));
  --scale-x: 1;
  --rotate: 0deg;
  transform: rotate(var(--rotate)) scaleX(var(--scale-x)) scale(var(--min-font-size-inv));
}
.textLayer .markedContent { display: contents; }
.textLayer span[role="img"] { -webkit-user-select: none; user-select: none; cursor: default; }
</style>
</head>
<body>

<!-- Scroll mode: vertical column of pages -->
<div id="scroll-container"></div>

<!-- Paged mode: one page + prev/next nav -->
<div id="paged-container">
  <div id="paged-page-wrap"></div>
  <div id="paged-nav">
    <button class="nav-btn" id="prev-btn" disabled>← Prev</button>
    <button class="nav-btn" id="next-btn" disabled>Next →</button>
  </div>
</div>

<!-- Worker blob URL must be set before pdf.mjs is evaluated -->
<script>${workerBlobScript}</script>

<!-- pdf.js main library (inlined from pdfjs-dist/build/pdf.mjs) -->
<script type="module">
${pdfJsSrc}

// ── pdf.js API — reference via the global pdfjsLib that pdf.mjs sets. Do NOT
// destructure into local consts: pdf.mjs already declares top-level bindings
// named GlobalWorkerOptions/getDocument/TextLayer in THIS module scope, so
// re-declaring them throws "Identifier GlobalWorkerOptions has already been
// declared". We use pdfjsLib dot name everywhere instead.

// Worker setup. A real module Worker from the blob URL is the fast path; if the
// WebView blocks it (older engine), fall back to workerSrc (pdf.js fake worker
// on the main thread). A broken worker is a likely cause of a hang, so we
// surface failures rather than letting it stall.
try {
  pdfjsLib.GlobalWorkerOptions.workerPort = new Worker(window.__workerSrc, { type: 'module' });
} catch (e) {
  window.__postToRN({ type: 'error', message: 'worker-spawn-failed: ' + String(e) });
  pdfjsLib.GlobalWorkerOptions.workerSrc = window.__workerSrc;
}

// ── State ──
let pdfDoc = null;
let currentPage = 1;
let numPages = 0;
let mode = 'scroll'; // 'scroll' | 'paged'
let renderingPages = new Set();
let pageHeights = new Map(); // pageNum → natural CSS height
let scrollObserver = null;
let pendingPageInScroll = 1;

// Display width = viewport width minus padding
function getDisplayWidth() {
  return Math.max(240, window.innerWidth - 24);
}

// ── Bridge helpers ──
function postToRN(msg) {
  if (window.ReactNativeWebView) {
    window.ReactNativeWebView.postMessage(JSON.stringify(msg));
  }
}

// ── Render a single page into a container ──
async function renderPage(pageNum, container) {
  if (renderingPages.has(pageNum)) return;
  renderingPages.add(pageNum);

  try {
    const page = await pdfDoc.getPage(pageNum);
    const displayWidth = getDisplayWidth();
    const naturalVp = page.getViewport({ scale: 1 });
    const scale = displayWidth / naturalVp.width;
    const dpr = window.devicePixelRatio || 1;
    const canvasScale = scale * dpr;
    const viewport = page.getViewport({ scale: canvasScale });
    const cssH = viewport.height / dpr;

    // Remove placeholder if any
    container.innerHTML = '';
    container.classList.remove('page-placeholder');
    container.classList.add('page-wrap');
    container.style.width = displayWidth + 'px';
    container.style.height = cssH + 'px';

    pageHeights.set(pageNum, cssH);

    // Canvas
    const canvas = document.createElement('canvas');
    canvas.width = viewport.width;
    canvas.height = viewport.height;
    canvas.style.width = displayWidth + 'px';
    canvas.style.height = cssH + 'px';
    canvas.style.display = 'block';
    container.appendChild(canvas);

    const ctx = canvas.getContext('2d');
    const renderTask = page.render({ canvas, viewport });
    await renderTask.promise;

    // Text layer (transparent, selectable) + geometry extraction (05c-3)
    try {
      const textContent = await page.getTextContent();
      // Post raw geometry to RN using the scale-1 viewport (naturalVp).
      // Fires even for text-empty pages so RN always receives a geometry message.
      postToRN({
        type: 'geometry',
        pageNumber: pageNum,
        viewport: { width: naturalVp.width, height: naturalVp.height },
        items: textContent.items,
      });
      if (textContent.items.length > 0) {
        const textDiv = document.createElement('div');
        textDiv.className = 'textLayer';
        // --total-scale-factor: CSS scale (display px per PDF unit),
        // independent of DPR (matches 05a pdf-page.tsx)
        textDiv.style.setProperty('--total-scale-factor', String(scale));
        const textLayer = new pdfjsLib.TextLayer({
          textContentSource: textContent,
          container: textDiv,
          viewport: page.getViewport({ scale }),
        });
        await textLayer.render();
        container.appendChild(textDiv);
      }
    } catch {
      // Text layer is non-fatal (scanned/image PDF)
    }

    page.cleanup();
  } catch (err) {
    renderingPages.delete(pageNum);
    // Rendering a page is non-fatal in scroll mode (placeholder stays)
    console.error('[ember-reader] renderPage error', pageNum, err);
  }
}

// ── Scroll mode rendering with IntersectionObserver virtualization ──
const ACTIVE_BUFFER = 2; // pages above/below viewport to actively render

function buildScrollPages() {
  const container = document.getElementById('scroll-container');
  container.innerHTML = '';

  const displayWidth = getDisplayWidth();
  // A4 fallback height
  const a4H = displayWidth * (297 / 210);

  const entries = [];
  for (let i = 1; i <= numPages; i++) {
    const wrap = document.createElement('div');
    wrap.className = 'page-placeholder';
    wrap.dataset.page = String(i);
    const h = pageHeights.get(i) || a4H;
    wrap.style.width = displayWidth + 'px';
    wrap.style.height = Math.round(h) + 'px';
    container.appendChild(wrap);
    entries.push(wrap);
  }

  // IntersectionObserver: track the most-visible page and render ±ACTIVE_BUFFER
  const intersecting = new Set();
  scrollObserver = new IntersectionObserver((obs) => {
    for (const entry of obs) {
      const p = parseInt(entry.target.dataset.page, 10);
      if (entry.isIntersecting) intersecting.add(p);
      else intersecting.delete(p);
    }
    const visible = Array.from(intersecting).sort((a, b) => a - b);
    if (visible.length > 0) {
      const top = visible[0];
      if (top !== pendingPageInScroll) {
        pendingPageInScroll = top;
        currentPage = top;
        postToRN({ type: 'page', current: top });
      }
      // Render active window
      for (let p = Math.max(1, top - ACTIVE_BUFFER); p <= Math.min(numPages, top + ACTIVE_BUFFER); p++) {
        const el = container.querySelector('[data-page="' + p + '"]');
        if (el && !el.classList.contains('page-wrap')) {
          renderPage(p, el);
        }
      }
    }
  }, { threshold: 0.1 });

  for (const el of entries) scrollObserver.observe(el);
}

function buildPagedPage() {
  const wrap = document.getElementById('paged-page-wrap');
  wrap.innerHTML = '';
  const container = document.createElement('div');
  wrap.appendChild(container);
  renderPage(currentPage, container);

  document.getElementById('prev-btn').disabled = currentPage <= 1;
  document.getElementById('next-btn').disabled = currentPage >= numPages;
}

// ── Mode switch ──
function applyMode(newMode) {
  mode = newMode;
  const scrollEl = document.getElementById('scroll-container');
  const pagedEl = document.getElementById('paged-container');

  if (newMode === 'scroll') {
    pagedEl.style.display = 'none';
    scrollEl.style.display = 'flex';
    if (scrollObserver) scrollObserver.disconnect();
    renderingPages.clear();
    buildScrollPages();
  } else {
    scrollEl.style.display = 'none';
    pagedEl.style.display = 'flex';
    if (scrollObserver) { scrollObserver.disconnect(); scrollObserver = null; }
    renderingPages.clear();
    buildPagedPage();
  }
}

// ── Paged navigation ──
document.getElementById('prev-btn').addEventListener('click', () => {
  if (currentPage > 1) {
    currentPage--;
    renderingPages.clear();
    buildPagedPage();
    postToRN({ type: 'page', current: currentPage });
  }
});
document.getElementById('next-btn').addEventListener('click', () => {
  if (currentPage < numPages) {
    currentPage++;
    renderingPages.clear();
    buildPagedPage();
    postToRN({ type: 'page', current: currentPage });
  }
});

// ── Bridge message handler (RN → WebView) ──
window.addEventListener('message', handleMessage);
document.addEventListener('message', handleMessage); // Android

// Handshake: the ~3MB pdf.js module above has finished evaluating and our
// message listener is now attached. Tell RN it is safe to post load/mode/theme.
// react-native-webview postMessage is NOT queued, so RN MUST wait for this
// before posting, otherwise the initial load is dropped and the reader hangs
// on the spinner forever.
postToRN({ type: 'bootReady' });

function handleMessage(event) {
  let msg;
  try { msg = JSON.parse(event.data); } catch { return; }

  switch (msg.type) {
    case 'load': {
      loadPdf(msg.bytesBase64);
      break;
    }
    case 'setMode': {
      if (msg.mode === mode) break;
      // Store the requested mode even before the doc loads, so loadPdf's
      // applyMode(mode) builds the correct initial view (e.g. opening in paged).
      mode = msg.mode;
      if (pdfDoc) applyMode(mode);
      break;
    }
    case 'setTheme': {
      document.documentElement.setAttribute('data-reader-theme', msg.theme);
      break;
    }
    case 'gotoPage': {
      if (!pdfDoc) break;
      const p = Math.max(1, Math.min(numPages, msg.page));
      if (mode === 'paged') {
        currentPage = p;
        renderingPages.clear();
        buildPagedPage();
        postToRN({ type: 'page', current: currentPage });
      } else {
        // Scroll to the page element
        const el = document.querySelector('#scroll-container [data-page="' + p + '"]');
        if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
      break;
    }
  }
}

// ── Load PDF from base64 bytes ──
async function loadPdf(bytesBase64) {
  try {
    postToRN({ type: 'stage', stage: 'decoding' });
    // Decode base64 → Uint8Array
    const binaryStr = atob(bytesBase64);
    const bytes = new Uint8Array(binaryStr.length);
    for (let i = 0; i < binaryStr.length; i++) bytes[i] = binaryStr.charCodeAt(i);

    postToRN({ type: 'stage', stage: 'getDocument' });
    pdfDoc = await pdfjsLib.getDocument({ data: bytes }).promise;
    numPages = pdfDoc.numPages;
    currentPage = 1;
    pendingPageInScroll = 1;
    renderingPages.clear();
    pageHeights.clear();

    postToRN({ type: 'ready', numPages });
    applyMode(mode); // build the initial view
  } catch (err) {
    postToRN({ type: 'error', message: String(err) });
  }
}
</script>
</body>
</html>`;
}
