/**
 * build-reader-html.ts — generates the self-contained WebView HTML for the PDF reader.
 *
 * ASSET-LOADING MECHANISM (documented per spec):
 * We use `source={{ html: buildReaderHtml(pdfJsSrc, pdfWorkerSrc) }}` with pdf.js
 * content injected as inline <script> tags. This avoids file:// URI resolution
 * differences between iOS and Android in Expo Go, requires no custom Metro config,
 * and keeps the reader fully offline (no network).
 *
 * pdf.js and pdf.worker.mjs content is generated at build time by
 * `scripts/bundle-pdfjs.mjs` into `src/reader/pdf-js-content.ts` (gitignored,
 * regenerated by `predev`/`prebuild`). The worker is injected as a Blob URL so
 * pdf.js can find it via `GlobalWorkerOptions.workerSrc`.
 *
 * Reader themes (paper/sepia/night) are applied via `data-reader-theme` on <html>
 * + CSS custom properties that match ui-context.md values exactly (no token pipeline
 * available inside the WebView HTML).
 *
 * Bridge messages:
 *   RN → WebView: { type:'load', bytesBase64 } | { type:'setMode', mode } |
 *                 { type:'setTheme', theme } |
 *                 { type:'gotoPage', page, offset? }
 *                   scroll mode: scrolls to pageEl.offsetTop + offset * pageEl.offsetHeight
 *                   paged mode:  offset ignored, navigates to the page
 *   WebView → RN: { type:'ready', numPages } | { type:'page', current } |
 *                 { type:'position', page, offset }  (capture signal; debounced on scroll-settle)
 *                 { type:'error', message? } |
 *                 { type:'geometry', pageNumber, viewport:{width,height}, items } |
 *                 { type:'selection', page, startChar, endChar, rect:{x,y,width,height} } |
 *                 { type:'selectionCleared' }
 *   RN → WebView (10d additions):
 *                 { type:'setAnnotations', items:[{id,page,kind,color,boxes}] } |
 *                 { type:'clearSelection' }
 */

// ── Reader palette (must match ui-context.md exactly — no token pipeline here) ──
// paper #FBF6EC / #2A2422 · sepia #F2E5CC / #4A3F2F · night #14110E / #C9BEAD
const READER_PALETTE = {
  paper: { bg: '#FBF6EC', text: '#2A2422', pageBorder: '#E7DDCB' },
  sepia: { bg: '#F2E5CC', text: '#4A3F2F', pageBorder: '#D4C5A6' },
  night: { bg: '#14110E', text: '#C9BEAD', pageBorder: '#2A2420' },
} as const;

// ── Highlight palette (must match packages/tokens/src/theme.uniwind.css exactly) ──
// --color-highlight-yellow: #f4d06f  --color-highlight-green: #9fc08a
// --color-highlight-blue:   #93b7d4  --color-highlight-pink:  #e3a7be
// No token pipeline available in the WebView HTML — same constraint as READER_PALETTE.
// Injected into the template via JSON.stringify so the value is the single source of
// truth checked by the build-reader-html.test.ts parity assertions.
const HIGHLIGHT_HEX: Record<string, string> = {
  yellow: '#f4d06f',
  green:  '#9fc08a',
  blue:   '#93b7d4',
  pink:   '#e3a7be',
};

export function buildReaderHtml(pdfJsSrc: string, pdfWorkerSrc: string): string {
  // Build worker blob script — injected inline so pdf.js can set workerSrc to
  // a blob URL. This avoids needing a separate worker file accessible via file://.
  // Classic (non-module) script: runs during parse, BEFORE the pdf.js module.
  // Defines postToRN + global error handlers so that an uncaught error while
  // evaluating the 3MB pdf.js module (or anywhere) is reported to RN instead of
  // leaving the reader on an infinite spinner. Also builds the worker blob URL.
  const workerBlobScript = `
    function postToRN(msg) {
      if (window.ReactNativeWebView) {
        window.ReactNativeWebView.postMessage(JSON.stringify(msg));
      }
    }
    window.__postToRN = postToRN;
    window.addEventListener('error', function (e) {
      postToRN({ type: 'error', message: 'js-error: ' + (e && e.message ? e.message : String(e)) });
    });
    window.addEventListener('unhandledrejection', function (e) {
      postToRN({ type: 'error', message: 'unhandled-rejection: ' + String(e && e.reason) });
    });
    var __workerSrc = (function() {
      var blob = new Blob([${JSON.stringify(pdfWorkerSrc)}], { type: 'application/javascript' });
      return URL.createObjectURL(blob);
    })();
  `;

  const paletteCSS = Object.entries(READER_PALETTE)
    .map(
      ([theme, { bg, text, pageBorder }]) => `
    html[data-reader-theme="${theme}"] {
      --reader-bg: ${bg};
      --reader-text: ${text};
      --reader-page-border: ${pageBorder};
    }`,
    )
    .join('\n');

  return `<!DOCTYPE html>
<html data-reader-theme="paper" lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=3.0">
<title>Ember Reader</title>
<style>
/* ── Reset ── */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

/* ── Reader palette (per-theme, toggled via data-reader-theme) ── */
${paletteCSS}

html, body {
  background: var(--reader-bg, #FBF6EC);
  color: var(--reader-text, #2A2422);
  font-family: -apple-system, system-ui, sans-serif;
  min-height: 100%;
}

/* ── Scroll mode ── */
#scroll-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 24px;
  padding: 24px 12px;
}

/* ── Paged mode ── */
#paged-container {
  display: none;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  padding: 16px 12px 80px;
}

#paged-nav {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
  padding: 12px 16px;
  background: var(--reader-bg, #FBF6EC);
  border-top: 1px solid var(--reader-page-border, #E7DDCB);
}

.nav-btn {
  font-size: 14px;
  padding: 8px 18px;
  border-radius: 6px;
  border: 1px solid var(--reader-page-border, #E7DDCB);
  background: var(--reader-bg, #FBF6EC);
  color: var(--reader-text, #2A2422);
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  transition: opacity 0.15s;
}
.nav-btn:disabled { opacity: 0.3; cursor: default; }
.nav-btn:not(:disabled):active { opacity: 0.6; }

/* ── Page wrapper ── */
.page-wrap {
  position: relative;
  border-radius: 3px;
  overflow: hidden;
  border: 1px solid var(--reader-page-border, #E7DDCB);
  box-shadow: 0 1px 4px rgba(0,0,0,0.08);
  flex-shrink: 0;
}

/* ── Placeholder (unrendered pages in scroll mode) ── */
.page-placeholder {
  background: var(--reader-bg, #FBF6EC);
  border-radius: 3px;
  border: 1px solid var(--reader-page-border, #E7DDCB);
  flex-shrink: 0;
}

/* ── pdf.js text layer (selectable overlay) ──────────────────────────────────
 * Structural rules lifted from pdfjs-dist/web/pdf_viewer.css (v6). The
 * TextLayer renders transparent, absolutely-positioned glyphs over the page
 * canvas so text is selectable. --total-scale-factor is set per-page.
 * ─────────────────────────────────────────────────────────────────────────── */
.textLayer {
  --min-font-size: 1;
  --text-scale-factor: calc(var(--total-scale-factor) * var(--min-font-size));
  --min-font-size-inv: calc(1 / var(--min-font-size));
  position: absolute;
  text-align: initial;
  inset: 0;
  overflow: clip;
  opacity: 1;
  line-height: 1;
  letter-spacing: normal;
  word-spacing: normal;
  text-size-adjust: none;
  forced-color-adjust: none;
  transform-origin: 0 0;
  z-index: 0;
}
.textLayer :is(span, br) {
  color: transparent;
  position: absolute;
  white-space: pre;
  cursor: text;
  transform-origin: 0% 0%;
  -webkit-user-select: text;
  user-select: text;
}
.textLayer > :not(.markedContent),
.textLayer .markedContent span:not(.markedContent) {
  z-index: 1;
  --font-height: 0;
  font-size: calc(var(--text-scale-factor) * var(--font-height));
  --scale-x: 1;
  --rotate: 0deg;
  transform: rotate(var(--rotate)) scaleX(var(--scale-x)) scale(var(--min-font-size-inv));
}
.textLayer .markedContent { display: contents; }
.textLayer span[role="img"] { -webkit-user-select: none; user-select: none; cursor: default; }

/* ── Highlight paint layer (10d) ─────────────────────────────────────────────
 * .ember-hl overlays are absolutely-positioned inside .page-wrap, above the
 * canvas but non-interactive (tap-to-edit is 10e). The per-theme blend mode
 * (multiply on paper/sepia, screen on night) keeps the tint legible on all
 * backgrounds — same approach as 10b's --highlight-blend token.
 * ─────────────────────────────────────────────────────────────────────────── */
.ember-hl {
  position: absolute;
  pointer-events: none;
  border-radius: 2px;
  /* Default blend: multiply (paper / sepia) */
  mix-blend-mode: multiply;
}
html[data-reader-theme="night"] .ember-hl {
  mix-blend-mode: screen;
}
</style>
</head>
<body>

<!-- Scroll mode: vertical column of pages -->
<div id="scroll-container"></div>

<!-- Paged mode: one page + prev/next nav -->
<div id="paged-container">
  <div id="paged-page-wrap"></div>
  <div id="paged-nav">
    <button class="nav-btn" id="prev-btn" disabled>← Prev</button>
    <button class="nav-btn" id="next-btn" disabled>Next →</button>
  </div>
</div>

<!-- Worker blob URL must be set before pdf.mjs is evaluated -->
<script>${workerBlobScript}</script>

<!-- pdf.js main library (inlined from pdfjs-dist/build/pdf.mjs) -->
<script type="module">
${pdfJsSrc}

// ── pdf.js API — reference via the global pdfjsLib that pdf.mjs sets. Do NOT
// destructure into local consts: pdf.mjs already declares top-level bindings
// named GlobalWorkerOptions/getDocument/TextLayer in THIS module scope, so
// re-declaring them throws "Identifier GlobalWorkerOptions has already been
// declared". We use pdfjsLib dot name everywhere instead.

// Worker setup. A real module Worker from the blob URL is the fast path; if the
// WebView blocks it (older engine), fall back to workerSrc (pdf.js fake worker
// on the main thread). A broken worker is a likely cause of a hang, so we
// surface failures rather than letting it stall.
try {
  pdfjsLib.GlobalWorkerOptions.workerPort = new Worker(window.__workerSrc, { type: 'module' });
} catch (e) {
  window.__postToRN({ type: 'error', message: 'worker-spawn-failed: ' + String(e) });
  pdfjsLib.GlobalWorkerOptions.workerSrc = window.__workerSrc;
}

// ── State ──
let pdfDoc = null;
let currentPage = 1;
let numPages = 0;
let mode = 'scroll'; // 'scroll' | 'paged'
let renderingPages = new Set();
let pageHeights = new Map(); // pageNum → natural CSS height
let scrollObserver = null;
let pendingPageInScroll = 1;
let scrollSettleTimer = null; // debounce handle for position capture

// ── 10d: Highlight paint state ──
// Keyed by page number; each value is the items array for that page from the last
// setAnnotations message. Cleared and rebuilt on every setAnnotations post.
let annotationsByPage = new Map(); // pageNum → [{id, kind, color, boxes}]

// ── 10d: Highlight palette (must match packages/tokens/src/theme.uniwind.css exactly) ──
// Injected via JSON.stringify from the TS constant above so the parity test can assert
// on the same value without duplicating the hex strings inside the template literal.
var HIGHLIGHT_HEX = ${JSON.stringify(HIGHLIGHT_HEX)};

// ── 10d: Selection debounce timer ──
let selectionTimer = null;

// Display width = viewport width minus padding
function getDisplayWidth() {
  return Math.max(240, window.innerWidth - 24);
}

// ── Bridge helpers ──
function postToRN(msg) {
  if (window.ReactNativeWebView) {
    window.ReactNativeWebView.postMessage(JSON.stringify(msg));
  }
}

// ── Render a single page into a container ──
async function renderPage(pageNum, container) {
  if (renderingPages.has(pageNum)) return;
  renderingPages.add(pageNum);

  try {
    const page = await pdfDoc.getPage(pageNum);
    const displayWidth = getDisplayWidth();
    const naturalVp = page.getViewport({ scale: 1 });
    const scale = displayWidth / naturalVp.width;
    const dpr = window.devicePixelRatio || 1;
    const canvasScale = scale * dpr;
    const viewport = page.getViewport({ scale: canvasScale });
    const cssH = viewport.height / dpr;

    // Remove placeholder if any
    container.innerHTML = '';
    container.classList.remove('page-placeholder');
    container.classList.add('page-wrap');
    container.style.width = displayWidth + 'px';
    container.style.height = cssH + 'px';

    pageHeights.set(pageNum, cssH);

    // Canvas
    const canvas = document.createElement('canvas');
    canvas.width = viewport.width;
    canvas.height = viewport.height;
    canvas.style.width = displayWidth + 'px';
    canvas.style.height = cssH + 'px';
    canvas.style.display = 'block';
    container.appendChild(canvas);

    const ctx = canvas.getContext('2d');
    const renderTask = page.render({ canvas, viewport });
    await renderTask.promise;

    // Text layer (transparent, selectable) + geometry extraction (05c-3)
    try {
      const textContent = await page.getTextContent();
      // Post raw geometry to RN using the scale-1 viewport (naturalVp).
      // Fires even for text-empty pages so RN always receives a geometry message.
      postToRN({
        type: 'geometry',
        pageNumber: pageNum,
        viewport: { width: naturalVp.width, height: naturalVp.height },
        items: textContent.items,
      });
      if (textContent.items.length > 0) {
        const textDiv = document.createElement('div');
        textDiv.className = 'textLayer';
        // --total-scale-factor: CSS scale (display px per PDF unit),
        // independent of DPR (matches 05a pdf-page.tsx)
        textDiv.style.setProperty('--total-scale-factor', String(scale));
        const textLayer = new pdfjsLib.TextLayer({
          textContentSource: textContent,
          container: textDiv,
          viewport: page.getViewport({ scale }),
        });
        await textLayer.render();
        container.appendChild(textDiv);
      }
    } catch {
      // Text layer is non-fatal (scanned/image PDF)
    }

    // 10d: Paint any known highlights onto the freshly-rendered page.
    // Called at the END of renderPage so lazily virtualized pages paint when
    // they render. Also re-painted immediately for already-rendered pages when
    // a setAnnotations message arrives.
    paintAnnotations(pageNum, container);

    page.cleanup();
  } catch (err) {
    renderingPages.delete(pageNum);
    // Rendering a page is non-fatal in scroll mode (placeholder stays)
    console.error('[ember-reader] renderPage error', pageNum, err);
  }
}

// ── 10d: Highlight paint layer ────────────────────────────────────────────────

// Paint annotation overlays for pageNum into wrapEl.
// Clears prior .ember-hl nodes first so re-paints on setAnnotations are clean.
// Each box is expressed as fractions of page dimensions (resolved by RN via core).
function paintAnnotations(pageNum, wrapEl) {
  // Remove any existing highlight overlays for this page.
  const prior = wrapEl.querySelectorAll('.ember-hl');
  for (var i = 0; i < prior.length; i++) prior[i].parentNode.removeChild(prior[i]);

  var items = annotationsByPage.get(pageNum);
  if (!items || items.length === 0) return;

  var W = wrapEl.offsetWidth;
  var H = wrapEl.offsetHeight;

  for (var j = 0; j < items.length; j++) {
    var item = items[j];
    var boxes = item.boxes;
    var hexColor = HIGHLIGHT_HEX[item.color] || HIGHLIGHT_HEX.yellow;
    for (var k = 0; k < boxes.length; k++) {
      var box = boxes[k];
      var el = document.createElement('div');
      el.className = 'ember-hl';
      el.style.left   = (box.x * W) + 'px';
      el.style.top    = (box.y * H) + 'px';
      el.style.width  = (box.width * W) + 'px';
      el.style.height = (box.height * H) + 'px';
      // ~50% alpha tint; blend mode is controlled by CSS (.ember-hl per-theme rule)
      el.style.backgroundColor = hexColor + '80'; // 80 hex ≈ 50% opacity
      wrapEl.appendChild(el);
    }
  }
}

// ── 10d: Selection capture bridge ────────────────────────────────────────────

// Compute the char offset of (node, offsetInNode) within root's text nodes,
// using a TreeWalker sum — same algorithm as web's charOffsetOf in selection-anchor.ts.
// Returns -1 when the node is not found under root.
function charOffsetOf(root, node, offsetInNode) {
  var walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  var accumulated = 0;
  var current = walker.nextNode();
  while (current !== null) {
    if (current === node) return accumulated + offsetInNode;
    accumulated += current.length;
    current = walker.nextNode();
  }
  return -1;
}

// Debounced selection handler: fires ~250 ms after the last selectionchange or
// touchend, posts { type:'selection', page, startChar, endChar, rect } to RN,
// or { type:'selectionCleared' } when the selection collapses.
function handleSelectionChange() {
  if (selectionTimer !== null) clearTimeout(selectionTimer);
  selectionTimer = setTimeout(function () {
    selectionTimer = null;
    var sel = window.getSelection();
    if (!sel || sel.isCollapsed || sel.rangeCount === 0) {
      postToRN({ type: 'selectionCleared' });
      return;
    }

    var range = sel.getRangeAt(0);

    // Find the .textLayer ancestor of the selection's anchor node.
    var startNode = range.startContainer;
    var textLayer = null;
    var n = startNode.nodeType === Node.TEXT_NODE ? startNode.parentNode : startNode;
    while (n) {
      if (n.classList && n.classList.contains('textLayer')) { textLayer = n; break; }
      n = n.parentNode;
    }
    if (!textLayer) { postToRN({ type: 'selectionCleared' }); return; }

    // Find the .page-wrap containing this text layer (walk up from textLayer).
    var pageWrap = textLayer.parentNode;
    while (pageWrap && !(pageWrap.classList && pageWrap.classList.contains('page-wrap'))) {
      pageWrap = pageWrap.parentNode;
    }
    if (!pageWrap || !pageWrap.dataset.page) { postToRN({ type: 'selectionCleared' }); return; }

    var page = parseInt(pageWrap.dataset.page, 10);

    var startChar = charOffsetOf(textLayer, range.startContainer, range.startOffset);
    if (startChar < 0) { postToRN({ type: 'selectionCleared' }); return; }

    var endChar = charOffsetOf(textLayer, range.endContainer, range.endOffset);
    if (endChar < 0) {
      // End node is outside this page's text layer (cross-page drag): clip to page text length.
      var walker2 = document.createTreeWalker(textLayer, NodeFilter.SHOW_TEXT);
      var total = 0;
      var cur = walker2.nextNode();
      while (cur !== null) { total += cur.length; cur = walker2.nextNode(); }
      endChar = total;
    }

    if (startChar === endChar) { postToRN({ type: 'selectionCleared' }); return; }

    var rect = range.getBoundingClientRect();
    postToRN({
      type: 'selection',
      page: page,
      startChar: startChar,
      endChar: endChar,
      rect: { x: rect.left, y: rect.top, width: rect.width, height: rect.height },
    });
  }, 250);
}

document.addEventListener('selectionchange', handleSelectionChange);
document.addEventListener('touchend', handleSelectionChange);

// ── Scroll mode rendering with IntersectionObserver virtualization ──
const ACTIVE_BUFFER = 2; // pages above/below viewport to actively render

function buildScrollPages() {
  const container = document.getElementById('scroll-container');
  container.innerHTML = '';

  const displayWidth = getDisplayWidth();
  // A4 fallback height
  const a4H = displayWidth * (297 / 210);

  const entries = [];
  for (let i = 1; i <= numPages; i++) {
    const wrap = document.createElement('div');
    wrap.className = 'page-placeholder';
    wrap.dataset.page = String(i);
    const h = pageHeights.get(i) || a4H;
    wrap.style.width = displayWidth + 'px';
    wrap.style.height = Math.round(h) + 'px';
    container.appendChild(wrap);
    entries.push(wrap);
  }

  // IntersectionObserver: track the most-visible page and render ±ACTIVE_BUFFER
  const intersecting = new Set();
  scrollObserver = new IntersectionObserver((obs) => {
    for (const entry of obs) {
      const p = parseInt(entry.target.dataset.page, 10);
      if (entry.isIntersecting) intersecting.add(p);
      else intersecting.delete(p);
    }
    const visible = Array.from(intersecting).sort((a, b) => a - b);
    if (visible.length > 0) {
      const top = visible[0];
      if (top !== pendingPageInScroll) {
        pendingPageInScroll = top;
        currentPage = top;
        postToRN({ type: 'page', current: top });
      }
      // Render active window
      for (let p = Math.max(1, top - ACTIVE_BUFFER); p <= Math.min(numPages, top + ACTIVE_BUFFER); p++) {
        const el = container.querySelector('[data-page="' + p + '"]');
        if (el && !el.classList.contains('page-wrap')) {
          renderPage(p, el);
        }
      }
    }
  }, { threshold: 0.1 });

  // Scroll-settle position capture: debounce on window scroll, post {type:'position'}
  // ~150 ms after the last scroll event. Uses rAF for timing accuracy.
  function onScrollSettle() {
    if (scrollSettleTimer !== null) clearTimeout(scrollSettleTimer);
    scrollSettleTimer = setTimeout(function () {
      scrollSettleTimer = null;
      // Find the topmost visible page element
      const allPages = container.querySelectorAll('[data-page]');
      let topPage = currentPage;
      let topOffset = 0;
      for (const el of allPages) {
        const rect = el.getBoundingClientRect();
        // Use the first page that overlaps the viewport top
        if (rect.bottom > 0 && rect.top <= window.innerHeight) {
          const p = parseInt(el.dataset.page, 10);
          const elH = el.offsetHeight;
          const scrolledIntoEl = Math.max(0, -rect.top);
          const offset = elH > 0 ? Math.min(1, Math.max(0, scrolledIntoEl / elH)) : 0;
          topPage = p;
          topOffset = offset;
          break;
        }
      }
      postToRN({ type: 'position', page: topPage, offset: topOffset });
    }, 150);
  }
  window.addEventListener('scroll', onScrollSettle, { passive: true });

  for (const el of entries) scrollObserver.observe(el);
}

function buildPagedPage() {
  const wrap = document.getElementById('paged-page-wrap');
  wrap.innerHTML = '';
  const container = document.createElement('div');
  // Match scroll mode: stamp the page number so selection capture and the
  // setAnnotations repaint (both keyed on .page-wrap[data-page]) work in paged mode.
  container.dataset.page = String(currentPage);
  wrap.appendChild(container);
  renderPage(currentPage, container);

  document.getElementById('prev-btn').disabled = currentPage <= 1;
  document.getElementById('next-btn').disabled = currentPage >= numPages;
}

// ── Mode switch ──
function applyMode(newMode) {
  mode = newMode;
  const scrollEl = document.getElementById('scroll-container');
  const pagedEl = document.getElementById('paged-container');

  if (newMode === 'scroll') {
    pagedEl.style.display = 'none';
    scrollEl.style.display = 'flex';
    if (scrollObserver) scrollObserver.disconnect();
    renderingPages.clear();
    buildScrollPages();
  } else {
    scrollEl.style.display = 'none';
    pagedEl.style.display = 'flex';
    if (scrollObserver) { scrollObserver.disconnect(); scrollObserver = null; }
    renderingPages.clear();
    buildPagedPage();
  }
}

// ── Paged navigation ──
document.getElementById('prev-btn').addEventListener('click', () => {
  if (currentPage > 1) {
    currentPage--;
    renderingPages.clear();
    buildPagedPage();
    postToRN({ type: 'page', current: currentPage });
    postToRN({ type: 'position', page: currentPage, offset: 0 });
  }
});
document.getElementById('next-btn').addEventListener('click', () => {
  if (currentPage < numPages) {
    currentPage++;
    renderingPages.clear();
    buildPagedPage();
    postToRN({ type: 'page', current: currentPage });
    postToRN({ type: 'position', page: currentPage, offset: 0 });
  }
});

// ── Bridge message handler (RN → WebView) ──
window.addEventListener('message', handleMessage);
document.addEventListener('message', handleMessage); // Android

// Handshake: the ~3MB pdf.js module above has finished evaluating and our
// message listener is now attached. Tell RN it is safe to post load/mode/theme.
// react-native-webview postMessage is NOT queued, so RN MUST wait for this
// before posting, otherwise the initial load is dropped and the reader hangs
// on the spinner forever.
postToRN({ type: 'bootReady' });

function handleMessage(event) {
  let msg;
  try { msg = JSON.parse(event.data); } catch { return; }

  switch (msg.type) {
    case 'load': {
      loadPdf(msg.bytesBase64);
      break;
    }
    case 'setMode': {
      if (msg.mode === mode) break;
      // Store the requested mode even before the doc loads, so loadPdf's
      // applyMode(mode) builds the correct initial view (e.g. opening in paged).
      mode = msg.mode;
      if (pdfDoc) applyMode(mode);
      break;
    }
    case 'setTheme': {
      document.documentElement.setAttribute('data-reader-theme', msg.theme);
      break;
    }
    case 'gotoPage': {
      if (!pdfDoc) break;
      const p = Math.max(1, Math.min(numPages, msg.page));
      if (mode === 'paged') {
        currentPage = p;
        renderingPages.clear();
        buildPagedPage();
        postToRN({ type: 'page', current: currentPage });
        // offset is ignored in paged mode (whole page in view, resume to page top)
      } else {
        // Scroll mode: restore to the saved fractional offset within the page.
        // pageEl.offsetTop gives the absolute scroll position of the page top;
        // adding offset * offsetHeight lands the saved fraction at the viewport top.
        const el = document.querySelector('#scroll-container [data-page="' + p + '"]');
        if (el) {
          const offset = typeof msg.offset === 'number' ? Math.min(1, Math.max(0, msg.offset)) : 0;
          const targetY = el.offsetTop + offset * el.offsetHeight;
          window.scrollTo({ top: targetY, behavior: 'smooth' });
        }
      }
      break;
    }
    case 'setAnnotations': {
      // Rebuild the per-page annotation map, then repaint all already-rendered pages.
      // Lazily virtualized pages pick up the annotations in paintAnnotations at the
      // END of renderPage, so no explicit queuing needed.
      annotationsByPage = new Map();
      var items = msg.items || [];
      for (var i = 0; i < items.length; i++) {
        var it = items[i];
        var bucket = annotationsByPage.get(it.page) || [];
        bucket.push(it);
        annotationsByPage.set(it.page, bucket);
      }
      // Repaint already-rendered page-wraps immediately.
      var rendered = document.querySelectorAll('.page-wrap[data-page]');
      for (var r = 0; r < rendered.length; r++) {
        var pageNum = parseInt(rendered[r].dataset.page, 10);
        paintAnnotations(pageNum, rendered[r]);
      }
      break;
    }
    case 'clearSelection': {
      // RN asks the WebView to drop the active DOM selection (after highlight created).
      if (window.getSelection) window.getSelection().removeAllRanges();
      break;
    }
  }
}

// ── Load PDF from base64 bytes ──
async function loadPdf(bytesBase64) {
  try {
    postToRN({ type: 'stage', stage: 'decoding' });
    // Decode base64 → Uint8Array
    const binaryStr = atob(bytesBase64);
    const bytes = new Uint8Array(binaryStr.length);
    for (let i = 0; i < binaryStr.length; i++) bytes[i] = binaryStr.charCodeAt(i);

    postToRN({ type: 'stage', stage: 'getDocument' });
    pdfDoc = await pdfjsLib.getDocument({ data: bytes }).promise;
    numPages = pdfDoc.numPages;
    currentPage = 1;
    pendingPageInScroll = 1;
    renderingPages.clear();
    pageHeights.clear();

    postToRN({ type: 'ready', numPages });
    applyMode(mode); // build the initial view
  } catch (err) {
    postToRN({ type: 'error', message: String(err) });
  }
}
</script>
</body>
</html>`;
}
